version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: ./ml_microservices/auth/Dockerfile
    container_name: auth_service
    ports:
      - "3001:3001"
    restart: always

  upload-service:
    build:
      context: .
      dockerfile: ./ml_microservices/upload/Dockerfile
    container_name: upload_service
    ports:
      - "3002:3002"
    volumes:
      - ./ml_microservices/upload/uploads:/app/uploads
    depends_on:
      - auth-service
    restart: always

  predict-service:
    build:
      context: .
      dockerfile: ./ml_microservices/predict/Dockerfile
    container_name: predict_service
    ports:
      - "3003:3003"
    volumes:
      - ./model:/app/model
      - ./ml_microservices/upload/uploads:/app/uploads
    depends_on:
      - upload-service
    restart: always

  train-service:
    build:
      context: .
      dockerfile: ./ml_microservices/train/Dockerfile
    container_name: train_service
    ports:
      - "3004:3004"
    volumes:
      - ./model:/app/model
      - ./data/train:/app/data/train
    depends_on:
      - predict-service
    restart: always
